### ISSUE TITLE
Xdebug Version not upped

### ISSUE THREAD

**Issue by styks1987** [geerlingguy/ansible-role-php-xdebug#18]
The task Move Xdebug module into place gets skipped when a new version is inserted. Therefore, you have to manually move the xdebug.so into place if you upgrade the xdebug version. Any chance this could check to see if a new version has been updated?

**Comment by geerlingguy** [comment]
Hmm, sounds like a good idea, but I don't have a quick fix for it... next time I work on this role more I'll try to take a look, otherwise anyone viewing this can leave a PR for me to review.

**Comment by joestewart** [comment]
#30 will correct this issue too.

**Comment by geerlingguy** [comment]
This should be working now.
