### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-php-xdebug#21]
It looks like maybe we need to fix https://github.com/geerlingguy/ansible-role-php/issues/53 upstream to make sure the cli has xdebug available? Or something... ugh, always something.

See failing test: https://travis-ci.org/geerlingguy/ansible-role-php-xdebug/builds/107860584

**Comment by oxyc** [comment]
This is fixed.

**Comment by geerlingguy** [comment]
Thanks for mentioning :)
