### ISSUE TITLE
Cannot use php to disable xdebug

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-php-xdebug#22]
Trying to disable the xdebug plugin to improve composer performance:

```
php -dextension=/usr/lib/php5/modules/xdebug.so
PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0
PHP Warning:  Module 'xdebug' already loaded in Unknown on line 0
```

**Comment by fubarhouse** [comment]
Not sure if it's related to that error, but I'm using NGINX, I also have apache2 but the service is off.
The command being used for reference is ````sudo php5dismod xdebug````

**Comment by fubarhouse** [comment]
Here's an alternative:
````
php -dextension=/usr/lib/php5/modules/xdebug.so
PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0
PHP Warning:  Module 'xdebug' already loaded in Unknown on line 0
````

**Comment by thom8** [comment]
Depending on your OS and PHP version you could try `sudo php5dismod xdebug` otherwise you need to unlink the xdebug.ini for the php cli config.

For ubuntu 14.04 -- `sudo php5dismod -s cli xdebug` disables xdebug & `sudo php5enmod -s cli xdebug` will enable only for php cli.
