### ISSUE TITLE
Add bash scripts to enable / disable xdebug

### ISSUE THREAD

**Issue by FinBoWa** [geerlingguy/ansible-role-php-xdebug#24]
I'd suggest that there should be a param 

```
enable_xdebug_so: true
```

That would be check if you want the role enable the library directly. 

And also add a bash script what you could use to call on host to restore/remove the lines.

**Comment by geerlingguy** [comment]
@FinBoWa - I would rather (at least for now) recommend just setting up a tag (in your own playbooks) or using Drupal VM's `xdebug` tag to just run the xdebug-related provisioning tasks. This should be almost as fast as logging into the server and calling out a shell script.

See docs specifically for Drupal VM: http://docs.drupalvm.com/en/latest/extending/ansible-args/#run-a-specific-set-of-tagged-tasks
