### ISSUE TITLE
How to override ansible j2 template (xdebug.ini.j2)?

### ISSUE THREAD

**Issue by kenorb** [geerlingguy/ansible-role-php-xdebug#29]
I'd like to override existing `xdebug.ini.j2` template file. Similar to [ansible-role-php](https://github.com/geerlingguy/ansible-role-php).

I'm using [drupalvm](https://github.com/geerlingguy/drupal-vm).

Is it possible without changing the original template? I've tried copying the template, but it didn't work.

**Comment by oxyc** [comment]
It does not. https://github.com/geerlingguy/ansible-role-php-xdebug/blob/master/tasks/configure.yml#L4 would need to be a variable rather than a hardcoded string.
