### ISSUE TITLE
Doesn't work with PHP 7.1

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/ansible-role-php-xdebug#37]
On Ubuntu 14.04 with PHP 7.1

> failed: [drupalvm_php] (item=./configure) => {"changed": true, "cmd": "./configure", "delta": "0:00:01.001059", "end": "2016-12-10 01:18:03.169708", "failed": true, "item": "./configure", "rc": 1, "start": "2016-12-10 01:18:02.168649", "stderr": "configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.\nconfigure: error: not supported. Need a PHP version >= 5.4.0 and < 7.1.0 (found 7.1.0-3+deb.sury.org~trusty+1)", "stdout": "checking for grep that handles long lines and -e... /bin/grep\nchecking for egrep... /bin/grep -E\nchecking for a sed that does not truncate output... /bin/sed\nchecking for cc... cc\nchecking whether the C compiler works... yes\nchecking for C compiler default output file name... a.out\nchecking for suffix of executables... \nchecking whether we are cross compiling... no\nchecking for suffix of object files... o\nchecking whether we are using the GNU C compiler... yes\nchecking whether cc accepts -g... yes\nchecking for cc option to accept ISO C89... none needed\nchecking how to run the C preprocessor... cc -E\nchecking for icc... no\nchecking for suncc... no\nchecking whether cc understands -c and -o together... yes\nchecking for system library directory... lib\nchecking if compiler supports -R... no\nchecking if compiler supports -Wl,-rpath,... yes\nchecking build system type... x86_64-unknown-linux-gnu\nchecking host system type... x86_64-unknown-linux-gnu\nchecking target system type... x86_64-unknown-linux-gnu\nchecking for PHP prefix... /usr\nchecking for PHP includes... -I/usr/include/php/20160303 -I/usr/include/php/20160303/main -I/usr/include/php/20160303/TSRM -I/usr/include/php/20160303/Zend -I/usr/include/php/20160303/ext -I/usr/include/php/20160303/ext/date/lib\nchecking for PHP extension directory... /usr/lib/php/20160303\nchecking for PHP installed headers prefix... /usr/include/php/20160303\nchecking if debug is enabled... no\nchecking if zts is enabled... no\nchecking for re2c... no\nchecking for gawk... no\nchecking for nawk... nawk\nchecking if nawk is broken... no\nchecking whether to enable Xdebug support... yes, shared\nchecking Check for supported PHP versions... ", "stdout_lines": ["checking for grep that handles long lines and -e... /bin/grep", "checking for egrep... /bin/grep -E", "checking for a sed that does not truncate output... /bin/sed", "checking for cc... cc", "checking whether the C compiler works... yes", "checking for C compiler default output file name... a.out", "checking for suffix of executables... ", "checking whether we are cross compiling... no", "checking for suffix of object files... o", "checking whether we are using the GNU C compiler... yes", "checking whether cc accepts -g... yes", "checking for cc option to accept ISO C89... none needed", "checking how to run the C preprocessor... cc -E", "checking for icc... no", "checking for suncc... no", "checking whether cc understands -c and -o together... yes", "checking for system library directory... lib", "checking if compiler supports -R... no", "checking if compiler supports -Wl,-rpath,... yes", "checking build system type... x86_64-unknown-linux-gnu", "checking host system type... x86_64-unknown-linux-gnu", "checking target system type... x86_64-unknown-linux-gnu", "checking for PHP prefix... /usr", "checking for PHP includes... -I/usr/include/php/20160303 -I/usr/include/php/20160303/main -I/usr/include/php/20160303/TSRM -I/usr/include/php/20160303/Zend -I/usr/include/php/20160303/ext -I/usr/include/php/20160303/ext/date/lib", "checking for PHP extension directory... /usr/lib/php/20160303", "checking for PHP installed headers prefix... /usr/include/php/20160303", "checking if debug is enabled... no", "checking if zts is enabled... no", "checking for re2c... no", "checking for gawk... no", "checking for nawk... nawk", "checking if nawk is broken... no", "checking whether to enable Xdebug support... yes, shared", "checking Check for supported PHP versions... "], "warnings": []}
failed: [drupalvm_php] (item=make) => {"changed": true, "cmd": "make", "delta": "0:00:00.011378", "end": "2016-12-10 01:18:03.442383", "failed": true, "item": "make", "rc": 2, "start": "2016-12-10 01:18:03.431005", "stderr": "make: *** No targets specified and no makefile found.  Stop.", "stdout": "", "stdout_lines": [], "warnings": []}

https://github.com/oerdnj/deb.sury.org/issues/444

**Comment by geerlingguy** [comment]
This was fixed a while back in the above PR :)
