### ISSUE TITLE
Task "Move Xdebug module into place" failing

### ISSUE THREAD

**Issue by kentr** [geerlingguy/ansible-role-php-xdebug#43]
### Problem / motivation

I'm getting repeated errors at the `Move Xdebug module into place` task.

The error message is

```
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/root/php7.0/xdebug-2.5.0/modules/xdebug.so' in expected paths."}
```

### Steps to reproduce

1. Clone DrupalVM
2. Uncomment `xdebug` in `installed_extras`.
3. `vagrant up`.

### Suggested fix

Revert the `Move Xdebug module into place` task so that it uses the `shell` module instead of the `copy` module.

Maybe `copy` module is working in some cases here, but the Ansible docs claim that it's for copying a file from the local machine to the remote node, not for copying a file within the remote node.

Limited testing shows that this change solves the problem in my case.

PR coming.

**Comment by oxyc** [comment]
Hmm I think the `copy` task is missing `remote_src: yes`

**Comment by kentr** [comment]
Ah, right.  I'm running it now with that change to confirm.

**Comment by kentr** [comment]
@oxyc I was wondering about the tests, too.
