### ISSUE TITLE
Configuration option to completely unload xdebug extension for CLI

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/ansible-role-php-xdebug#53]
Following up on conversation here: https://github.com/geerlingguy/drupal-vm/issues/1545

Having xdebug loaded for the CLI (even if it's not enabled) has a significant performance impact: https://github.com/acquia/blt/pull/1983#issuecomment-328942432

Currently, if you set `php_xdebug_default_enable: 0` or `php_xdebug_cli_enable: 0` in config.yml, xdebug will be disabled for the CLI, but will still be loaded, causing said performance issues.

There should be a way to have the xdebug extension completely unloaded for CLI by default.

**Comment by geerlingguy** [comment]
I seem to remember there is... I think we discussed it in the Drupal VM queue a while back.

**Comment by geerlingguy** [comment]
https://github.com/geerlingguy/drupal-vm/issues/112 was one place we discussed this, but you're saying you'd like a quick way to say "remove this from php.ini entirely (no xdebug.so)", I'm guessing?

**Comment by geerlingguy** [comment]
Because as a short term workaround, you could maybe run `vagrant exec "rm -f /etc/php/7.1/mods-available/xdebug.ini && sudo systemctl restart php7.1-fpm"` (assuming you're using Debian 9, Ubuntu 16.04, and PHP 7.1... adjust accordingly for older versions).

**Comment by joestewart** [comment]
To disable for CLI only on Ubuntu vm's I've used a similar line like:
```
vagrant ssh -c "sudo mv /etc/php/7.0/cli/conf.d/20-xdebug.ini /etc/php/7.0/cli/conf.d/20-xdebug.ini.disabled"
```

Also have done a similar post provision task to do the same thing by default.  

This is easier on Debian style with multiple configuration directories.

**Comment by geerlingguy** [comment]
Yeah, my way kinda nukes things until you run another `vagrant provision`. It's one of the few cases where I do kinda-sorta appreciate the way Debian-based distros organize config files.

Note that the role was originally written for repeatable deploys / 12-factor-style use, where you build something once, and it's that way until you rebuild it from scratch. But for the purposes of local dev, especially with this one extension that _does_ create strife if you leave it enabled when not in use... I'd be willing to merge a PR that adds some sort of task that disables the extension (either by removing or moving the file).

Maybe just `if php_xdebug_default_enable, then delete the ini file`?

**Comment by joestewart** [comment]
Also previously discussed in issue #34

**Comment by danepowell** [comment]
I know how to manually kill xdebug (just comment out or delete the 20-xdebug.ini file), but what I'm asking for is a way to make that configurable via `config.yml`. So that a project (such as one created by BLT) would have xdebug completely disabled for CLI by default, but individual developers could override this in their local config if they really wanted.

I think this is the logic I'm looking for (minor tweak):
`if NOT php_xdebug_default_enable, then delete the ini file and restart php handler`

Although... won't that kill xdebug for apache/fpm as well? I only need to kill it for the CLI, I think most folks would want to keep it enabled for apache/fpm.

**Comment by JorisVanEijden** [comment]
Here's a package to restart CLI commands with xdebug disabled: https://github.com/composer/xdebug-handler
