### ISSUE TITLE
Does not support PHP 7.2

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/ansible-role-php-xdebug#55]
Not much that can be done but posting it here to keep track of the issue. The latest XDebug v2.5.5 doesn't support PHP 7.2.

https://xdebug.org/updates.php#x_2_5_5

**Comment by geerlingguy** [comment]
Aww. And possibly related? https://bugs.xdebug.org/view.php?id=1420

**Comment by emirb** [comment]
The above mentioned bug is closed now.

**Comment by joelpittet** [comment]
2.6.0 seems to work well so far. *holds breath*, i just installed it manually from source against 7.1

**Comment by oxyc** [comment]
@pminf just to verify, did you try setting the version? `php_xdebug_version: 2.5.0`

**Comment by oxyc** [comment]
Maybe the fix is just bumping the default version to 2.6.0 which should be done anyways.

**Comment by pminf** [comment]
@oxyc I can confirm, that setting `php_xdebug_version` to `2.6.0` resolves the issue, both 4.7.2 and 4.8.1.

**Comment by oxyc** [comment]
Could you send over a PR with the change in `README.md` as well as `defaults/main.yml` so @geerlingguy just has to press merge :)

**Comment by pminf** [comment]
Here you are, @geerlingguy: https://github.com/geerlingguy/ansible-role-php-xdebug/pull/58

**Comment by pminf** [comment]
We better update the docs to set Xdebug version to 2.5.0 if using PHP 5.x.

**Comment by geerlingguy** [comment]
PR is updated. But yeah, docs should be updated to. I'll do that and close out this issue.

**Comment by geerlingguy** [comment]
All good now; waiting on tests to come back green before tagging a new release.
