### ISSUE TITLE
Install is broken with PHP 5.4 in some cases with geerlinguy.php

### ISSUE THREAD

**Issue by ammont** [geerlingguy/ansible-role-php-xdebug#57]
I'm using your geerlinguy.php package to install php 7, when I try to install xdebug I get this error:

`ailed: [lsv3] (item=php-fpm) => {"changed": false, "item": "php-fpm", "msg": "Error: Package: php-fpm-5.4.16-43.el7_4.x86_64 (updates)\n           Requires: php-common(x86-64) = 5.4.16-43.el7_4\n           Installed: php-common-7.2.2-1.el7.remi.x86_64 (@remi-php72)\n               php-common(x86-64) = 7.2.2-1.el7.remi\n           Available: php-common-5.4.16-42.el7.x86_64 (base)\n               php-common(x86-64) = 5.4.16-42.el7\n           Available: php-common-5.4.16-43.el7_4.x86_64 (updates)\n               php-common(x86-64) = 5.4.16-43.el7_4\n", "rc": 1, "results": ["Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: mirrors.clouvider.net\n * epel: mirrors.coreix.net\n * extras: mirrors.coreix.net\n * remi-safe: mirror.netweaver.uk\n * updates: mirrors.clouvider.net\nResolving Dependencies\n--> Running transaction check\n---> Package php-fpm.x86_64 0:5.4.16-43.el7_4 will be installed\n--> Processing Dependency: php-common(x86-64) = 5.4.16-43.el7_4 for package: php-fpm-5.4.16-43.el7_4.x86_64\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}`

Seems this package is trying to install php packages from 5.4 version.

**Comment by geerlingguy** [comment]
Note that this seems to work fine with the PHP role in many of my projects including Drupal VM. I haven't used PHP 5.4 in a long time though. It looks like you might be using a really old version of the PHP role, or a really old OS?

Also take a look at using the php-versions role to grab a newer version of PHP more easily.

**Comment by ammont** [comment]
Thanks for your response @geerlingguy I installed PHP 7.2 using your php role then I tried to install xdebug using this role and that's when I got the error above. so my PHP is the latest version (7.2) and the OS I'm trying to provision is centos 7. any thoughts?

**Comment by geerlingguy** [comment]
CentOS 7 is one of the platforms that automated CI test builds are run on for this role, and they currently work fine, so please check out the playbook in the molecule directory and compare it to your own to see what might be different/causing issues.

Also, as I'm dropping PHP 5.x support (see https://github.com/geerlingguy/ansible-role-php-xdebug/issues/63), I am going to close this issue as it's originally related to 5.4 according to the title.
