### ISSUE TITLE
Xdebug stops on function definition in addition to breakpoint in 2.9.0

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/ansible-role-php-xdebug#64]
I ran into this bug on DrupalVM so I thought I'd share, may be worth bumping to `2.9.4`?

https://github.com/drud/ddev/issues/1996
https://twitter.com/derickr/status/1204864073252376610
https://youtrack.jetbrains.com/issue/WI-50152#focus=streamItem-27-3879179.0-0
https://bugs.xdebug.org/view.php?id=1727

But maybe it's as easy as setting `php_xdebug_version`... I'll try this but I thought I should report nonetheless.

**Comment by geerlingguy** [comment]
@joelpittet - Sorry for not seeing this sooner. Did 2.9.4 resolve the issue for you?

**Comment by joelpittet** [comment]
@geerlingguy Yes, sorry I am also not seeing things fast apparently ;)
