### ISSUE TITLE
Upgrade to 3.0.0

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/ansible-role-php-xdebug#65]
I was in the middle of a PR but the changes seem big so may warrant a discussion a bit.
https://php.watch/articles/xdebug2-vs-3-benchmark
https://xdebug.org/docs/upgrade_guide

Looks like much of the config has been replaced by a specific "mode"
```
xdebug.remote_enable=1
xdebug.default_enable=0
xdebug.profiler_enable=0
xdebug.auto_trace=0
xdebug.coverage_enable=0
```
becomes
```
xdebug.mode=debug
```

Default port changed from `9000` to `9003` (which is great because fpm always collides with it)

The `xdebug.remote_autostart` setting has been removed. Instead, set `xdebug.start_with_request` to `yes`.

So the big question, how much BC are you looking for @geerlingguy ?

**Comment by joelpittet** [comment]
Maybe still needs addressing?

**Comment by phizev** [comment]
I took a stab at starting to support both 2.x/3.x with behaviour changing by version. It very quickly spiralled out from there, maintaining full backwards compatibility appears to be far more work than I initially anticipated.

**Comment by GuillaumeGBzh** [comment]
Hi @geerlingguy,

Can you reopen this issue?

**Comment by geerlingguy** [comment]
We should do this :)

**Comment by jonnyeom** [comment]
Its been a while—

Xdebug 3.x supports php 7.2 and up.
Seeing that php 7.2 is end of life, I think its okay to break the BC.

Jeff,
If this is a good way to move forward, Ill make some readme updates as well

**Comment by kentr** [comment]
As this issue appears to be high-level regarding xdebug `3.x`, I wanted to note that [code coverage appears to enabled by `xdebug.mode=coverage`](https://xdebug.org/docs/upgrade_guide#changed-xdebug.coverage_enable). This matches my experience with using Laravel's `artisan test --coverage` feature.

Also note that `xdebug.mode` [can have multiple values](https://xdebug.org/docs/code_coverage#mode).

**Comment by kentr** [comment]
Also wanted to note: In my experience, the role will _install_ xdebug `3.x` (tested with `3.3.2`), but won't fully configure it.

**Comment by geerlingguy** [comment]
Definitely okay breaking bc now, I only support PHP 8.1+ now anyways, too hard to keep support for older versions.
