### ISSUE TITLE
A few php .ini files are in the wrong place on Ubuntu

### ISSUE THREAD

**Issue by mikecrittenden** [geerlingguy/ansible-role-php-xdebug#9]
Xdebug wasn't working for me immediately after install. Turns out that xdebug.ini was in /etc/php5/conf.d but Apache only cared about /etc/php5/apache2/conf.d (screenshot showing that: https://www.dropbox.com/s/3zgzpbrevy8f035/Screenshot%202015-04-17%2012.38.36.png?dl=0). Moving xdebug.ini into that directory and restarting apache fixed it.

I noticed that xhprof.ini and 20-apc.ini were also in the first directory, but not sure if those were broken as well.

This is on Ubuntu 14.04.

**Comment by mglaman** [comment]
:+1: I have this issue to and always end up copying it around

**Comment by mikebell** [comment]
This also occurs with php5-fpm

xdebug.ini exists in /etc/php5/conf.d so it needs copying to /etc/php5/fpm/conf.d

**Comment by arknoll** [comment]
PHPStorm didn't initially work when connected to drupal-vm. I had to:
```sudo cp /etc/php5/apache2/conf.d/xdebug.ini /etc/php5/cli/conf.d/xdebug.ini```

And then it worked.

**Comment by geerlingguy** [comment]
@arknoll - Thanks, I'll add that note too... basically the file is currently only copied inside the `apache2` dir on Ubuntu, but it should also be in `fpm` and `cli` as well. And it shouldn't be placed inside the main `/etc/php5/conf.d` necessarily...

Ugh, I hate Debian/Ubuntu-style pathing.

**Comment by geerlingguy** [comment]
@arknoll - In your case, it looks like setting `php_xdebug_cli_enable` to `1` would create the symlink. I'm going to default that to `1` for Drupal VM to prevent confusion in the future.

I'm working on the rest of this fix now.
